---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: znc-operator
  name: znc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: znc-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: znc-operator
    spec:
      serviceAccountName: znc-operator
      containers:
        - name: znc-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - znc-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "znc-operator"
...
